// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.5.0.4")]
[assembly: AssemblyFileVersionAttribute("1.5.0.4")]
[assembly: AssemblyInformationalVersionAttribute("1.5.0.4")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTrademarkAttribute("")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.5.0.4";
        internal const System.String AssemblyFileVersion = "1.5.0.4";
        internal const System.String AssemblyInformationalVersion = "1.5.0.4";
        internal const System.String AssemblyCompany = "";
        internal const System.String AssemblyCopyright = "";
        internal const System.String AssemblyTrademark = "";
    }
}
